### ISSUE TITLE
multi_socket_select_test failure

### ISSUE THREAD

**Issue by p** [p/pycurl-archived#22]
http://pastebin.mozilla.org/2210877

<pre>
======================================================================
FAIL: test_multi_socket_select (tests.multi_socket_select_test.MultiSocketSelectTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pie/apps/pycurl/tests/multi_socket_select_test.py", line 97, in test_multi_socket_select
    assert len(socket_events) >= 6, 'Less than 6 socket events: %s' % repr(socket_events)
AssertionError: Less than 6 socket events: [(1, <pycurl.CurlMulti object at 0x80514b620>), (1, <pycurl.CurlMulti object at 0x80514b620>), (4, <pycurl.CurlMulti object at 0x80514b620>), (4, <pycurl.CurlMulti object at 0x80514b620>)]

----------------------------------------------------------------------
Ran 46 tests in 5.982s

FAILED (errors=1, failures=1)
Exception in thread Thread-2 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 551, in __bootstrap_inner
  File "/home/pie/apps/pycurl/tests/runwsgi.py", line 55, in run
  File "/usr/local/bin/bottle.py", line 2434, in run
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
</pre>

**Comment by p** [comment]
http://pastebin.mozilla.org/2213404

This looks rather (more) wrong to me.
