### ISSUE TITLE
Installing pycurl with pip fails "Could not run curl-config: [Errno 2] No such file or directory: 'curl-config'"

### ISSUE THREAD

**Issue by BedivereZero** [p/pycurl-archived#55]
Installing pycurl with pip fails.

Python version:

```shell
$ python --version
Python 3.9.7
```

PIP version:

```shell
$ pip list
Package    Version
---------- -------
pip        22.0.4
setuptools 61.1.0
wheel      0.37.1
```

Install command:

```shell
$ pip install pycurl
Collecting pycurl
  Downloading pycurl-7.45.1.tar.gz (233 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.9/233.9 KB 103.5 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      /tmp/pip-install-bmja98xj/pycurl_1e41afdbec0548a28272100da2faf8e0/setup.py:957: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        if LooseVersion(distutils.__version__) > LooseVersion("1.0.1"):
      /tmp/pip-install-bmja98xj/pycurl_1e41afdbec0548a28272100da2faf8e0/setup.py:959: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        if LooseVersion(distutils.__version__) < LooseVersion("1.0.3"):
      Traceback (most recent call last):
        File "/tmp/pip-install-bmja98xj/pycurl_1e41afdbec0548a28272100da2faf8e0/setup.py", line 235, in configure_unix
          p = subprocess.Popen((self.curl_config(), '--version'),
        File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'curl-config'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-bmja98xj/pycurl_1e41afdbec0548a28272100da2faf8e0/setup.py", line 1017, in <module>
          ext = get_extension(sys.argv, split_extension_source=split_extension_source)
        File "/tmp/pip-install-bmja98xj/pycurl_1e41afdbec0548a28272100da2faf8e0/setup.py", line 673, in get_extension
          ext_config = ExtensionConfiguration(argv)
        File "/tmp/pip-install-bmja98xj/pycurl_1e41afdbec0548a28272100da2faf8e0/setup.py", line 99, in __init__
          self.configure()
        File "/tmp/pip-install-bmja98xj/pycurl_1e41afdbec0548a28272100da2faf8e0/setup.py", line 240, in configure_unix
          raise ConfigurationError(msg)
      __main__.ConfigurationError: Could not run curl-config: [Errno 2] No such file or directory: 'curl-config'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by BedivereZero** [comment]
Duplicate of pycurl/pycurl#722
